FROM adoptopenjdk:11-jre-hotspot
MAINTAINER Yegun Kim <wlfka102@gmail.com>

ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar

EXPOSE 8080
EXPOSE 5005

#디버깅을 하기 위해 docker-compose.yml의 "command" 에서 실행
#ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom", "-jar","/app.jar"]