FROM adoptopenjdk:11-jre-hotspot
MAINTAINER Yegun Kim <wlfka102@gmail.com>

ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar

EXPOSE 8080
EXPOSE 5005

#ENTRYPOINT ["java","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005","-Djava.security.egd=file:/dev/./urandom", "-jar","/app.jar"]