version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ibocon/cashflowbook
    container_name: cashflowbook
    network_mode: bridge
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - URL=jdbc:postgresql://postgres:5432/CashFlowBook
      - SECRET=${SECRET}
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=ENC(WywYnHdKMc9rUB3eYXEGAW8qkP/80vBA)
      - POSTGRES_USER=postgres
      - POSTGRES_DB=CashFlowBook
    restart: unless-stopped
volumes:
  postgres-data: