# Secret
jasypt:
  encryptor:
    password: ${SECRET}
    bean: jasyptEncryptor

# PostgresSQL
spring:
  datasource:
    url: ${URL}
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ENC(WywYnHdKMc9rUB3eYXEGAW8qkP/80vBA)
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none