server:
  port : 8080
  
# Secret
jasypt:
  encryptor:
    password: ${SECRET}
    bean: jasyptEncryptor

spring:
  data:
    rest:
      base-path : /api
  datasource:
    url: ${URL}
    username: postgres
    password: ENC(WywYnHdKMc9rUB3eYXEGAW8qkP/80vBA)
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
