server.port: 8081
logging.level.root: WARN

spring:
    h2.console.enabled: true
    datasource.url: jdbc:h2:mem:ledger;DB_CLOSE_ON_EXIT=FALSE
    jpa:
        open-in-view: false
        # 모델 변화에 맞춰 테이블 구조 변경
        hibernate.ddl-auto: update

    security:
        oauth2.client.registration.google:
            client-id: ENC(+bLv66PdqdHet39T3uIWyjRBC+8H9QyCV8es4UtDCe7SG8J74wmZI6z8IO29+sowQ6htogNsjFnJ4ZL9oYD5mKQxMZTHRhH7i4IPVmwHq18lajrUyUJEEg==)
            client-secret: ENC(ChxWAioKf+bAKlW/SswkQTFGU8e3GipxWrd714I2qFRk32I0SPdViw==)

jasypt.encryptor:
    bean: jasyptEncryptor
    password: ${SECRET}
    
ledger:
    jwt:
        secret: ${SECRET}
        expire: 86400000 # 1 d = 86400000 ms
    redirectUri: http://localhost:8080/oauth2/redirect
    
  