export const ActionConstant = {
    // GET_USERS: 'GET_USERS',
    SET_CURRENT_USER: 'GET_CURRENT_USER',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    GET_ACCOUNTS: 'GET_ACCOUNTS',
    SHOW_MODAL: 'SHOW_MODAL',
    REGISTER_ACCOUNT_HANDLER: 'REGISTER_ACCOUNT_HANDLER',
    CREATE_ACCOUNT: 'CREATE_ACCOUNT',
}

